import Head from '@/components/layout/Head';
import Navbar from '@/components/layout/Navbar';
import {Inter} from 'next/font/google'
const inter = Inter({subsets:['latin']})

// export const metadata = {
//   title: "store my car",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head/>
      <body className={inter.className}>
    <Navbar/>
<hr/>
        {children}
      </body>
    </html>
  );
}
