import React from 'react';
export const metadata = {
    title: " carsId",
    description: "Generated by create next app",
  };
const carsLayout = ({children}) => {
    return (
        <>
        <br />
        <br />
            <h1 >
                cars
            </h1>
            {children}
        </>
    );
}

export default carsLayout;
